name: dash_app #Environment name
dependencies:
- python=3.8.8
- dash=2.0.0
- plotly=5.1.0
- numpy=1.19.5
- pandas=1.1.5
- scipy=1.7.1
- scikit-image=0.18.1
- scikit-learn=0.23.2
- scipy=1.7.1
- xgboost=1.3.3
- gunicorn
- pip:
  - dash-bootstrap-components=1.0.3
  - dash-canvas=0.1.0
